name: haml
version: master
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  haml:
    command: haml
    plugs: [home]

parts:
  haml:
    source: .
    plugin: ruby
    build: gem build haml.gemspec
    install: gem install haml-*.gem --env-shebang
